#!/bin/sh

~/.config/local/$(/bin/hostname) &

xcompmgr -n &
#compton -cCGb --backend glx --vsync opengl &
xrandr --output DVI-I-1 --primary --right-of HDM-1
redshift -l 0:18 -b 1:0.7 -t 7000:3500 -m vidmode:screen=0 &
xrdb ~/.Xresources &

if [ -z $(pidof syncthing) ]
then
	syncthing -no-browser &
fi

if [ -n "${GPG_AGENT_INFO}" ]; then
	 kill $(echo ${GPG_AGENT_INFO} | cut -d':' -f 2) >/dev/null 2>&1
fi
gpg-agent --daemon --use-standard-socket &
